name: blogger
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^3.0.1
  google_fonts: ^2.2.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.17
  infinite_scroll_pagination: ^3.1.0
  anmolverma_in:
    git: https://github.com/oianmol/flutter_web_cv

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img.webp
    - assets/intellij.png
    - assets/android.png
